/** 
 *
 * @author Schubert Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 build:   </p>
 *
 * code was generated by the Schubert System </br>
 * Schubert system Copyright - NewPortBay LLC copy_right_range</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
 */

app.controller('Authentication', ['$scope', '$rootScope', '$location', '$state', '$window', '$q', '$http', '$ionicPopup', 'RestURL', 'People_testId','OpenFB',
  function ($scope, $rootScope, $location, $state, $window, $q, $http, $ionicPopup, RestURL, People_testId,OpenFB) {
    var self = $scope;

    self.signIn = function () {
      console.log('Sign In');

      var user = {
        "email": self.login.email,
        "passWord": self.login.password
      };

      $http.post(RestURL.baseURL + 'sloan_test/login/loginValidation/', user)
        .success(function (data) {
          // uncomment when fixed
          //if (data.responseSuccess === 'success') {
          //  if (!data.result.user.loggedIn) {
              $state.go('organization');
            //} else $state.go('profile');
          //}
        })
        .error(function (error) {
          console.warn('Sign In failed');
          console.warn(error);
        });
    };

    self.signUp = function () {
      console.log('Sign Up');

      var data = {
        "email": self.email,
        "firstName": "",
        "lastName": "",
        "phoneNumber": "",
        "passWord": self.password,
        "oldPassword": "",
        "userType": "",
        "loggedIn": false
      };

      $http.post(RestURL.baseURL + 'sloan_test/signup/create/', data)
        .success(function (data) {
          console.log('Account Created');

          var user = {
            "email": self.email,
            "passWord": self.password
          };

          $http.post(RestURL.baseURL + 'sloan_test/login/loginValidation/', user)
            .success(function (data) {
              // uncomment when fixed
              //if (data.responseSuccess === 'success') {
              //  if (!data.result.user.loggedIn) {
              $state.go('organization');
              //} else $state.go('profile');
              //}
            })
            .error(function (error) {
              console.warn('Sign In failed');
              console.warn(error);
            });
        })
        .error(function (error) {
          console.warn('Sign Up failed');
          console.warn(error);
        });
    };

    self.go = function (url) {
      $state.go(url);
    };

	$scope.facebookLogin = function () {
		 OpenFB.login('email').then(
                function () {                    
					OpenFB.get('/me').success(function (user) {
						$scope.showAlert("FB login succeeded"+user.id);							
					});					
                },
                function (msg) {
                    $scope.showAlert("OpenFB login failed"+msg);
                });
        };

		
		$scope.gpluslogin = function () {
  
			$window.plugins.googleplus.login(
				{},
				function (obj) {
				  $scope.showAlert("SUCCESS LOGIN: "+obj.email);
				  //document.querySelector("#feedback").innerHTML = "Hi, " + obj.displayName + ", " + obj.email;
				},
				function (msg) {				
				  $scope.showAlert("ERROR: "+msg);
				}
			);
	}
	
	
		$scope.showAlert = function(msg) {
		   var alertPopup = $ionicPopup.alert({
			  title: msg,
			  template: msg,
		   });
		   alertPopup.then(function(res) {
			  console.log('Thanks');
		   });

		};
  }]);
