package geppetto.Sloan_test_1_10000.hnb.service;

import java.util.ArrayList;

import javax.annotation.Resource;
import org.springframework.stereotype.Service;



import geppetto.Sloan_test_1_10000.hnb.domain.core.People_test;

import geppetto.Sloan_test_1_10000.hnb.dao.mysql.Landing_pageDao;

import geppetto.Sloan_test_1_10000.hnb.domain.core.GpUser;



/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Service("Landing_pageService")
public class Landing_pageService extends GpBaseService  {


	Landing_pageDao Landing_page_dao;


	public Landing_pageDao get_Landing_page_dao() {
		return Landing_page_dao;
	}


	@Resource(name="Landing_pageDao")
	public void set_Landing_page_dao(Landing_pageDao Landing_page_dao) {
		this.Landing_page_dao = Landing_page_dao;
	}



	//auths not ready at this time
	public People_test people_test_search_for_update(long id, GpUser user) throws Exception {


		try{
			People_test the_People_test;

			the_People_test = Landing_page_dao.people_test_search_for_update(id, user);

			return the_People_test;			

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());

		}
		return null;


	}

	//auths not ready at this time
	public People_test update_people_test(People_test People_test, GpUser user) throws Exception {


		try{
			People_test the_People_test;

			the_People_test = Landing_page_dao.update_people_test(People_test, user);

			return the_People_test;			

		}catch(Exception e){

			System.out.println("ServiceException: " + e.toString());

		}
		return null;


	}




}