package geppetto.Sloan_test_1_10000.hnb.dao.mysql.support.People_test;

import java.sql.Types;
import javax.sql.DataSource;

import org.springframework.jdbc.core.SqlParameter;
import org.springframework.jdbc.object.SqlUpdate;


/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public class People_testUpdateMapper extends SqlUpdate {


	public static  String SQL_UPDATE_PEOPLE_TEST = "";

	public People_testUpdateMapper(DataSource dataSource) {

		super(dataSource, SQL_UPDATE_PEOPLE_TEST);

		super.declareParameter(new SqlParameter("First_name", Types.VARCHAR));
		super.declareParameter(new SqlParameter("Last_name", Types.VARCHAR));
		super.declareParameter(new SqlParameter("Organization_id", Types.BIGINT));
		super.declareParameter(new SqlParameter("Id", Types.BIGINT));


	}

}