package geppetto.Sloan_test_1_10000.hnb.controller;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import geppetto.Sloan_test_1_10000.hnb.domain.core.GpUser;



/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public class GpBaseController {

	private GpUser theUser;
	protected final Log logger = LogFactory.getLog(this.getClass());

	public GpUser getUser(){

		return null;
	}

	public void setUser(GpUser user){

	}


}