package geppetto.Sloan_test_1_10000.hnb.domain.core;


/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public class People_test  {

		long Id;
		String First_name;
		String Last_name;
		long Organization_id;


	public void set_Id(long Id) {
		this.Id = Id;
	}


	public long get_Id() {
		return Id;
	}

	public void set_First_name(String First_name) {
		this.First_name = First_name;
	}


	public String get_First_name() {
		return First_name;
	}

	public void set_Last_name(String Last_name) {
		this.Last_name = Last_name;
	}


	public String get_Last_name() {
		return Last_name;
	}

	public void set_Organization_id(long Organization_id) {
		this.Organization_id = Organization_id;
	}


	public long get_Organization_id() {
		return Organization_id;
	}




}