package geppetto.Sloan_test_1_10000.hnb.domain.core;


/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public class Contract  {

		long Id;
		String Contract_name;
		String Contract_description;
		long Contract_start_date;
		String Contract_end_date;
		String Enter_Name;


	public void set_Id(long Id) {
		this.Id = Id;
	}


	public long get_Id() {
		return Id;
	}

	public void set_Contract_name(String Contract_name) {
		this.Contract_name = Contract_name;
	}


	public String get_Contract_name() {
		return Contract_name;
	}

	public void set_Contract_description(String Contract_description) {
		this.Contract_description = Contract_description;
	}


	public String get_Contract_description() {
		return Contract_description;
	}

	public void set_Contract_start_date(long Contract_start_date) {
		this.Contract_start_date = Contract_start_date;
	}


	public long get_Contract_start_date() {
		return Contract_start_date;
	}

	public void set_Contract_end_date(String Contract_end_date) {
		this.Contract_end_date = Contract_end_date;
	}


	public String get_Contract_end_date() {
		return Contract_end_date;
	}

	public void set_Enter_Name(String Enter_Name) {
		this.Enter_Name = Enter_Name;
	}


	public String get_Enter_Name() {
		return Enter_Name;
	}




}