package geppetto.Sloan_test_1_10000.hnb.domain.core;


/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public class Organization  {

		long Id;
		long Organization_name;
		String Description;
		String Parent_org_id;
		String Org_label;


	public void set_Id(long Id) {
		this.Id = Id;
	}


	public long get_Id() {
		return Id;
	}

	public void set_Organization_name(long Organization_name) {
		this.Organization_name = Organization_name;
	}


	public long get_Organization_name() {
		return Organization_name;
	}

	public void set_Description(String Description) {
		this.Description = Description;
	}


	public String get_Description() {
		return Description;
	}

	public void set_Parent_org_id(String Parent_org_id) {
		this.Parent_org_id = Parent_org_id;
	}


	public String get_Parent_org_id() {
		return Parent_org_id;
	}

	public void set_Org_label(String Org_label) {
		this.Org_label = Org_label;
	}


	public String get_Org_label() {
		return Org_label;
	}




}