package geppetto.Sloan_test_1_10000.hnb.domain.core;

import java.math.BigDecimal;

import java.math.BigDecimal;

import java.math.BigDecimal;


/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
 * build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
public class Services  {

		long Id;
		String Service_name;
		String Description;
		BigDecimal Cost_per_hour;
		BigDecimal Points_per_hour;
		long Flat_fee_points;
		BigDecimal Flat_fee;


	public void set_Id(long Id) {
		this.Id = Id;
	}


	public long get_Id() {
		return Id;
	}

	public void set_Service_name(String Service_name) {
		this.Service_name = Service_name;
	}


	public String get_Service_name() {
		return Service_name;
	}

	public void set_Description(String Description) {
		this.Description = Description;
	}


	public String get_Description() {
		return Description;
	}

	public void set_Cost_per_hour(BigDecimal Cost_per_hour) {
		this.Cost_per_hour = Cost_per_hour;
	}


	public BigDecimal get_Cost_per_hour() {
		return Cost_per_hour;
	}

	public void set_Points_per_hour(BigDecimal Points_per_hour) {
		this.Points_per_hour = Points_per_hour;
	}


	public BigDecimal get_Points_per_hour() {
		return Points_per_hour;
	}

	public void set_Flat_fee_points(long Flat_fee_points) {
		this.Flat_fee_points = Flat_fee_points;
	}


	public long get_Flat_fee_points() {
		return Flat_fee_points;
	}

	public void set_Flat_fee(BigDecimal Flat_fee) {
		this.Flat_fee = Flat_fee;
	}


	public BigDecimal get_Flat_fee() {
		return Flat_fee;
	}




}