/**
 *
 * @author Schubert Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Schubert System </br>
 * Schubert system Copyright - NewPortBay LLC copy_right_range</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

app.controller("Authentication", [ '$scope', '$rootScope', '$location', '$window', '$q', '$http', 'People_testId', '$ionicPopup',
				    function( $scope, $rootScope, $location, $window, $q, $http, People_testId, $ionicPopup) {





}]);


