/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Geppetto system Copyright - NewPortBay LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

app = angular.module('Sloan_test_1', ['ionic'])

.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if (window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
      cordova.plugins.Keyboard.disableScroll(true);

    }
    if (window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }
  });
})

.config(function($stateProvider, $urlRouterProvider) {

  $stateProvider

  // setup an abstract state for the tabs directive
    .state('app', {
    url: '/app',
    abstract: true,
    templateUrl: 'app/views/menu.html'
  })

  	.state('app.First_time_setup-en', {
      url: '/First_time_setup-en',
      views: {
        'menuContent': {
          templateUrl: 'app/views/en/First_time_setup-en.html',
  controller: 'First_time_setup'
        }
      }
    })
  	.state('app.Ft_set_up_org_selection-en', {
      url: '/Ft_set_up_org_selection-en',
      views: {
        'menuContent': {
          templateUrl: 'app/views/en/Ft_set_up_org_selection-en.html',
  controller: 'Landing_page'
        }
      }
    })


  // if none of the above states are matched, use this as the fallback
  $urlRouterProvider.otherwise('/app/First_time_setup-en');

})

.factory('People_testId', function () {
	var id = '';
	return {
		setId: function (id){
			this.id = id;
		},
		getId: function (){
			return this.id;
		}
	}
}).controller('MainCtrl', ['$scope', function($scope) {
	$scope.hideSidemenuBackButton = true;
	var top_menu_items;
	top_menu_items = $scope.menu_items = 
[

	{
		is_first_level: true,
		name: "First_time_setup",
		label: "first_time_setup",
		id: 181,
		screens: [
			{
				id: 293,
				is_first_level: false,
				name: "First_time_setup-en",
				label: "first_time_setup",
			},
			{
				id: 295,
				is_first_level: false,
				name: "First_time_setup-en",
				label: "first_time _setup",
			}		]	},
	{
		is_first_level: true,
		name: "Landing_page",
		label: "landing_page",
		id: 182,
		screens: [
			{
				id: 294,
				is_first_level: false,
				name: "Ft_set_up_org_selection-en",
				label: "select org screen",
			}		]	},
	{
		is_first_level: true,
		name: "Authentication",
		label: "login",
		id: 183,
		screens: 		]	},
	{
		is_first_level: true,
		name: "MailChimp Activity",
		label: "MailChimp",
		id: 184,
		screens: 		]	}
];
var getByParentId = function(id) {
	for (var i in top_menu_items) {
		if (top_menu_items[i].id == id) {
			return top_menu_items[i].screens;
		}
	}
}
$scope.showSubcategories = function(category) {
	$scope.menu_items = getByParentId(category.id);
	$scope.hideSidemenuBackButton = false;
};
$scope.showTopLevelCategories = function () {
	$scope.menu_items = top_menu_items;
	$scope.hideSidemenuBackButton = true;
};
}])
;