/**
 * 
 * @author Geppetto Generated Code</br> Date Created: </br>
 * @since </br> build:
 *        </p>
 * 
 * code was generated by the Geppetto System </br> Geppetto system Copyright -
 * NewPortBay LLC </br> The generated code is free to use by anyone
 * </p>
 * 
 * 
 * 
 */

var app = angular.module('Sloan_test_1', [ 'ngRoute', 'ngCookies',
		'ui.bootstrap', 'ui.grid', 'ui.grid.pagination',
		'ui.grid.resizeColumns', 'ui.grid.edit','facebook' ]);

// configure our routes
app.config(function($routeProvider,FacebookProvider) {
	FacebookProvider.init('1619632164961533');
	
	$routeProvider.when('/First_time_setup-en', {
		templateUrl : 'app/views/en-US/First_time_setup-en.html',
		controller : 'First_time_setup'
	}).when('/', {
		templateUrl : 'app/views/en-US/home.html'		
	}).when('/en-US/login/', {
		templateUrl : 'app/views/en-US/login.html',
		controller:'LoginController'
	}).when('/en-US/signup/', {
		templateUrl : 'app/views/en-US/Signup.html',
		controller:'SignUpController'
	}).when('/en-US/customer/',{
		templateUrl:'app/views/en-US/customer.html',
		controller:'CustomerController'
	}).when('/en-US/careGiver/',{
		templateUrl:'app/views/en-US/careGiver.html',
		controller:'CareGiverController'
	}).when('/en-US/Landing-Page',{
		templateUrl:'app/views/en-US/landing-Page.html',
		controller:'Landing_page'
	}).when('/en-Us/Organisations',{
		templateUrl:'app/views/en-US/Organisation.html',
		controller:'OrganisationController'
	}).when('/en-US/UserType',{
		templateUrl:'app/views/en-US/UserType.html',
		controller:'UserTypeController'
	}).when('/en-US/LookinFor',{
		templateUrl:'app/views/en-US/LookingFor.html'
	}).when('/en-US/IamA',{
		templateUrl:'app/views/en-US/IAmA.html'
	})
	.otherwise({
		templateUrl : 'app/views/en-US/login.html',
		controller : 'LoginController'
	});

});
