package geppetto.Sloan_test_1_10000.hnb.controller;

import java.util.ArrayList;

import javax.annotation.Resource;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RequestBody;


import geppetto.Sloan_test_1_10000.hnb.domain.core.People_test;

import geppetto.Sloan_test_1_10000.hnb.service.First_time_setupService;



/**
 * 
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p> 
 *
 * code was generated by the Geppetto System </br>
 * Gepppetto system Copyright - Geppetto LLC 2014 - 2015</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/
@Controller("First_time_setupController")
@RequestMapping("/First_time_setup")
public class First_time_setupController extends GpBaseController {


	First_time_setupService First_time_setup_service;


	public First_time_setupService get_First_time_setup_service() {
		return First_time_setup_service;
	}


	@Resource(name="First_time_setupService")
	public void set_First_time_setup_service(First_time_setupService First_time_setup_service) {
		this.First_time_setup_service = First_time_setup_service;
	}






}